# Generated by Django 2.2.5 on 2020-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200406_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='boards.Like'),
        ),
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='boards.Photo'),
        ),
    ]
