# Generated by Django 2.2.5 on 2020-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200407_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='pushed',
        ),
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.ManyToManyField(to='boards.Like'),
        ),
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ManyToManyField(to='boards.Photo'),
        ),
    ]
