# Generated by Django 2.2.5 on 2020-04-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20200424_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='boards'),
        ),
    ]
