# Generated by Django 2.2.5 on 2020-04-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20200427_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='isLocation',
        ),
    ]
