# Generated by Django 2.2.5 on 2020-04-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_remove_board_islocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='board',
            new_name='board_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='username',
        ),
    ]
