# Generated by Django 2.2.5 on 2020-04-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20200427_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='username',
            new_name='user',
        ),
    ]
