# Generated by Django 2.2.5 on 2020-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20200427_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
