# Generated by Django 2.2.5 on 2020-04-22 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200421_0402'),
        ('wishlists', '0002_auto_20200422_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='store',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='diningstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DiningStore'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
    ]
