# Generated by Django 2.2.5 on 2020-04-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ManyToManyField(blank=True, null=True, to='follows.Followed'),
        ),
        migrations.RemoveField(
            model_name='followed',
            name='members',
        ),
        migrations.AddField(
            model_name='followed',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
