# Generated by Django 2.2.5 on 2020-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_auto_20200406_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(related_name='_follow_following_+', to='follows.Follow'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ManyToManyField(related_name='_follow_followed_+', to='follows.Follow'),
        ),
        migrations.DeleteModel(
            name='Followed',
        ),
    ]
