# Generated by Django 2.2.5 on 2020-04-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200421_0402'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='contents',
        ),
        migrations.AddField(
            model_name='review',
            name='isLocation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DiningStore'),
        ),
    ]
