# Generated by Django 2.2.5 on 2020-04-25 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200424_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DiningStore'),
        ),
    ]
