# Generated by Django 2.2.5 on 2020-04-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200425_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='isLocation',
        ),
    ]
