# Generated by Django 2.2.5 on 2020-04-08 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Location'),
        ),
        migrations.AddField(
            model_name='tag',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Store'),
        ),
    ]
