# Generated by Django 2.2.5 on 2020-04-06 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0004_auto_20200406_1820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=120)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('comment_number', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='comments.Comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
