# Generated by Django 2.2.5 on 2020-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200407_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='comments.Comment_Like'),
        ),
    ]
