# Generated by Django 2.2.5 on 2020-04-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200422_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parents',
        ),
        migrations.DeleteModel(
            name='Comment_Like',
        ),
    ]
