<<<<<<< HEAD
# Generated by Django 3.0.4 on 2020-03-31 06:24
=======
# Generated by Django 2.2.5 on 2020-03-31 06:24
>>>>>>> 5225be8fccc6af55ece1b46ffaf6321f6c06e3b3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
