# Generated by Django 2.2.5 on 2020-04-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200406_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
