# Generated by Django 2.2.5 on 2020-04-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200406_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
    ]
